rsyslog/libfastjson

- DIFFERENCES
- json_object.c
Note that json-c also doesn't properly handle NUL bytes, it just
pretends to do so and has not clearly documented it doesn't.
> no longer support native NUL bytes, so enhance performance

- printbuf.c
Using the same q'n'd fix from eabae907c9d991143e17da278a239819f2e8ae1c for *printbuf.c* as well.
Q'n'D because there are systems who don't support `_GNU_SOURCE`. They won't like such hard coded defines.
> printbuf.c: Fix for implicit declaration of function 'vasprintf'

- Makefile.am
- tests/Makefile.am
Only export symbols from this name space. Note that this may
currently block some functionality actually required by user
programs. We will work towards checking and potentially
re-enabling and renaming this shortly. For now, it's important
to set the baseline. In theory, all that really should be
API should be covered by this change.
closes https://github.com/rsyslog/libfastjson/issues/11
> provide consistent external namespace fjson_*

- configure.ac
- json_c_version.c
- json_c_version.h
- json_inttypes.h
- json_object.c
- json_object.h
- json_util.c
- linkhash.c
- linkhash.h
- tests/parse_flags.c
- tests/test_locale.c
The _C was a left-over from the "json-c" name.
closes https://github.com/rsyslog/libfastjson/issues/20
> change macro names from FJSON_C_ to FJSON_

- Makefile.am
Don't change standard behaviour of 'distclean' and 'maintainer-clean'.
This is annoying for users which expect the default behaviour of a
standard autoconf/automake project.
See [1] which e.g. is explicit about 'maintainer-clean' *not* removing
anything which is necessary to run configure.
The current behaviour breaks the Debian tools when trying to build twice
in a row, as the 'distclean' step removes too many files.
[1] https://www.gnu.org/prep/standards/html_node/Standard-Targets.html
> build: stop changing behaviour of standard targets

- DIFFERENCES
- json.h
- json_object.h
- json_tokener.c
- json_tokener.h
- json_util.h
- linkhash.h
... primarily for rsyslog family of projects. This is needed for
smooth migration to new namespace. We can later decide if we
extend or drop that layer.
closes https://github.com/rsyslog/libfastjson/issues/31
> add a source code compatibility layer to json-c

- README.md
Trivial fix.
Related to that, should we drop README.html?
atm we have README (empty), README.md and README.html. That's a bit confusing imho.
> doc: fix libfastjson GitHub URL

- DIFFERENCES
- json_object.c
- json_object.h
- json_object_iterator.c
This provides access directly to the object's hash table, which is
bad because the use of hash tables is an implementation detail and
as such a caller should not depend on it. Actually, we may even
remove hash tables in newer versions and/or introduce alternative
data stores.
closes https://github.com/rsyslog/libfastjson/issues/58
> remove [f]json_object_get_object() API

- Makefile.am
- json.h
- json_object_iterator.c
- tests/Makefile.am
- tests/parse_flags.c
- tests/test1.c
- tests/test2.c
- tests/testReplaceExisting.c
- tests/test_charcase.c
- tests/test_locale.c
- tests/test_parse.c
- tests/test_set_serializer.c
Various smaller fixes / improvements.
The next step would be, moving the private header files from libfastjsoninclude_HEADERS to libfastjson_internal_la_SOURCES, i.e. make sure those are no longer installed.
I've updated this PR to include the changes for the header files.
Please comment on d6d5a0c, especially if you'd prefer a json_internal.h for the tests.
> Build system fixes

- Makefile.am
see also https://github.com/rsyslog/libfastjson/issues/12
> bump soversion in spite of API/ABI changes

- json_object.c
closes https://github.com/rsyslog/libfastjson/issues/81
> bugfix: fjson_object_object_get_ex segfaults if param "value" == NULL

- tests/test_obj_iter-del.c
Was not detected due to prequisites obviously not 100% correct on CI env.
> testbench: tool was not building cleanly

- tests/Makefile.am
- tests/test_obj_obj_get_ex-null.c
- tests/test_obj_obj_get_ex-null.test
see also https://github.com/rsyslog/libfastjson/issues/81
**This PR makes sure that the testbench actually detects the problems on all platforms.** As such, we expect it to FAIL!
> testbench: detect misadressing in fjson_object_object_get_ex()

- .travis.yml
note: the clang test will fail because of issue #64. This will be corrected when we merge the hash table replacement (soon).
> travis: run clang address sanitizer

- json.h
as we have removed hash tables. However, for existing applications we
need to mimic like it was there, actuallying removing it.
> function fjson_global_set_string_hash is no longer available nor needed

- README.md
Thanks to Anthony Biacco for reporting this.
closes https://github.com/rsyslog/libfastjson/issues/91
> fix invalid instructions in README

- configure.ac
This is actually *required* because the daily build scripts
depend on this type of quoting to create the daily build
version number (they require the closing brace in order to
avoid false positives when substituting the version number).
> quote version

- tests/test4.c
This is a follow-up for commit b5b92ae341cf38d4bd19f662a011860136433262
> Fix duplicate include of config.h

- json_object.c
- tests/Makefile.am
- tests/ucs_copyright_char.c
- tests/ucs_copyright_char.expected
- tests/ucs_copyright_char.test
bugfix: invalid Unicode escapes, could also potentially trigger segfault
They were caused by improper sign extension of signed char, leading to
invalid table access.
closes #107
closes #106
> Fix  PR #107, #106

- m4/atomic_operations.m4
- m4/atomic_operations_64bit.m4
In cross-compilation, it is impossible to run code at configure time to
detect the target specifics.
As such, AC_TRY_RUN fails miserably to detect reliably that atomic
intrisics are present in a toolchain, and decides they are not just
because this is cross-compilation.
Instead of AC_TRY_RUN, use AC_LINK_IFELSE that does not need to actually
run code, since all we're interested in is whether the intrisics are
present (or not). Fix both the 32- and 64-bit variants, even if the
latter is not used currently.
Fixes build failures detected by the Buildroot autobuilders, like:
http://autobuild.buildroot.org/results/23a/23ac0e742ed3a70ae4d038f8c9eadc23e708f671/build-end.log
http://autobuild.buildroot.org/results/192/1923d0b570adba494f83747a9610ea6ec35f5223/build-end.log
and many other cases, …
> m4: fix detection of atomics

- .gitignore
- Makefile.am
- json_object.h
- json_print.c
Hello,
I've added fjson_object_dump() and fjson_object_write() functions that make it possible to dump the json tree without having to dynamically allocate a string, and to write the tree to a FILE*.
Most of the code is simply copied from the functions that use the "printbuf" for writing the data. I have not touched the old printbuf-implementation, because some other code may still rely on it. However, in my opinion these printbuf-based functions (if it is desirable to keep them in the first place) can now be re-implemented to use the more flexible fjson_object_dump() function.
Emiel
> Dumping the tree, and writing to FILE*

- configure.ac
- json.h
- json_object.c
This permits to search for json keys in a case-sensitive way.
The default is "off", as this is against the JSON spec. However,
rsyslog needs this capability to increase usability inside the
variable system.
We add a new API call to switch between case-sensitive and
case-insensitive comparison, with case-sensitive being the default.
> add option for case-insensitive comparisons

- json_object.h
The json-c compatibility-layer macros for the foreach loop have not been
removed when the loop was removed in #51.
> Removed foreach macro from compatibility-layer.

- CI/check_codestyle.sh
- json_object.c
- json_print.c
- json_tokener.c
if fjson_object_object_add_ex() is used with option
FJSON_OBJECT_KEY_IS_CONSTANT, fjson_object_object_del() will still
try to delete the key name. Depending on use, this can lead to
double-free, use-after-free or no problem.
see also https://github.com/rsyslog/rsyslog/issues/1839
closes https://github.com/rsyslog/libfastjson/issues/148
> bugfix: constant key names not properly handled

- arraylist.c
- arraylist.h
- json_object.c
- json_object.h
Adding "void fjson_object_array_del_idx(struct fjson_object *jso, int idx)",
which deletes the idx-th element in the array type object.
This patch is a part of work to support a requirement to remove empty json objects in parsing JSON.
Adding parse_json_ex to grammar/rainerscript.c for supporting compact.
Adding parameters variable, alt_variable and compact to mmjsonparse.
> Adding a function fjson_object_array_del_idx

- json_object.c
Actually, that warning is overly conservative, and so we
have changed the code in a somewhat suboptimal way to "fix"
it. In this spots, it's not that bad and we wanted to avoid
totally disabling this warning.
If it were more costly in terms of cleanness, we would probaly
have done that. Just mention it to tell anyone else the
cure is not really a good one, just selected due to the
circumstances in this special case.
> "fix" "jump-misses-init" gcc-8 warning

- json_object.c
- json_object.h
Add a function to get uint32_t representation of json-object.
This will help fix rsyslog issue #4490 and #3394.
> Add a function to get uint32_t representation of json-object

- arraylist.c
The other functions assume that the memory is either set to NULL or a valid JSON object. The array_list_del_idx function only moves the elements but does not set the pointer to null, which causes the same pointer to remain in the list (outside of arr->length). Then, when array_list_put_idx is called, the array_list_expand_internal leaps out, meaning that it has not set the indices outside of the requested length to 0. array_list_put_idx finds the pointer, tries to free it and a double free will be incurred because the actual element is still in the list.
Is triggered when an array is created, an element is removed and subsequently, a new element is inserted again. 
This can also be fixed by checking in the array_list_put_idx function, but as the arrays are explicitly calloc'ed and set to …
> bugfix for dangling pointer that causes segfault in array deletion and re-insertion.
